### PR TITLE
Add config for haskell, typescript, css, and scss

### PR DESCRIPTION
**Pull request by p-tupe**

### CODE REVIEW

**Comment by p-tupe** [comment]
Have checked the code in my local plugin against those types. 

Did not run bust tests, however. I'm not well-versed in lua environment. 

Hope this helps!

**Comment by gennaro-tedesco** [comment]
Thank you for your contribution, I will check the pull request later on in the afternoon. Meanwhile 

> Did not run bust tests, however.

I can run the tests: would it be possible to provide a test mock set-up [like this](https://github.com/gennaro-tedesco/nvim-commaround/blob/c9eb3e07caad10e8029eb55f94b119d8fd405de1/lua/spec/is_comment_spec.lua#L14-L21)? Essentially you would just need to provide a lua table of strings with the comment characters so that the test can check the function works as intended against those types too.

**Comment by p-tupe** [comment]
You're welcome! 

About the test mock set-up, I'm a bit hesitant to make changes in spec file and commit. I'm not confident I won't mess it up somehow especially since I can't run it. 

How does this code look :

```lua
describe("testing block comments", function()
   local comments = require("nvim-commaround.commaround")
   local global_config = require("nvim-commaround.config")
   local lua_ft_cfg, sql_ft_cfg, vim_ft_cfg, py_ft_cfg, hs_cfg, ts_cfg, css_cfg, scss_cfg

   setup(function()
	  lua_ft_cfg = global_config.config['lua']
	  sql_ft_cfg = global_config.config['sql']
	  vim_ft_cfg = global_config.config['vim']
	  py_ft_cfg = global_config.config['python']
	  hs_ft_cfg = global_config.config['haskell']
	  ts_ft_cfg = global_config.config['typescript']
	  css_ft_cfg = global_config.config['css']
	  scss_ft_cfg = global_config.config['scss']
   end)

   it("is_comment_block_surround #surround", function()
	  local lua_lines = {" --[[ first line", "second line", "third line ]]"}
	  assert.is_true(comments.is_comment_block_surround(lua_ft_cfg, lua_lines))

	  local sql_lines = {" /* first line", "second line", "third line */"}
	  assert.is_true(comments.is_comment_block_surround(sql_ft_cfg, sql_lines))

	  local hs_lines = {" {- first line", "second line", "third line -}"}
	  assert.is_true(comments.is_comment_block_surround(hs_ft_cfg, hs_lines))

	  local ts_lines = {" /* first line", "second line", "third line */"}
	  assert.is_true(comments.is_comment_block_surround(ts_ft_cfg, ts_lines))

	  local css_lines = {" /* first line", "second line", "third line */"}
	  assert.is_true(comments.is_comment_block_surround(css_ft_cfg, css_lines))

	  local scss_lines = {" /* first line", "second line", "third line */"}
	  assert.is_true(comments.is_comment_block_surround(scss_ft_cfg, scss_lines))

          assert.is_false(comments.is_comment_block_surround(sql_ft_cfg, lua_lines))
          assert.is_false(comments.is_comment_block_surround(lua_ft_cfg, sql_lines))
          assert.is_false(comments.is_comment_block_surround(hs_ft_cfg, hs_lines))
          assert.is_false(comments.is_comment_block_surround(ts_ft_cfg, ts_lines))
          assert.is_false(comments.is_comment_block_surround(css_ft_cfg, css_lines))
          assert.is_false(comments.is_comment_block_surround(scss_ft_cfg, scss_lines))
   end)

   it("is_comment_block_multiline #multiline", function()
	  local vim_lines = {"\" first line", "\" second line", "\" third line"}
	  assert.is_true(comments.is_comment_block_multiline(vim_ft_cfg, vim_lines))

	  local py_lines = {"# first line", "# second line", "# third line"}
	  assert.is_true(comments.is_comment_block_multiline(py_ft_cfg, py_lines))

          local hs_lines = {"-- first line", "-- second line", "-- third line"}
	  assert.is_true(comments.is_comment_block_surround(hs_ft_cfg, hs_lines))

	  local ts_lines = {"// first line", "// second line", "// third line"}
	  assert.is_true(comments.is_comment_block_surround(ts_ft_cfg, ts_lines))

	  local css_lines = {"// first line", "// second line", "// third line"}
	  assert.is_true(comments.is_comment_block_surround(css_ft_cfg, css_lines))

	  local scss_lines = {"// first line", "// second line", "// third line"}
	  assert.is_true(comments.is_comment_block_surround(scss_ft_cfg, scss_lines))
   end)

end)
```

**Comment by gennaro-tedesco** [comment]
It looks good at first sight. I will create a new branch off yours, later, and test the code. You could then make another check yourself and if all is good we merge to master.

**Comment by gennaro-tedesco** [comment]
I have branched off yours and created [this merge request](https://github.com/gennaro-tedesco/nvim-commaround/pull/7), which essentially is yours plus a test for haskell file types (I have omitted the other ones since their strings `/*` are already tested, so they should just work).

Please have a look if it works as intended so that we can merge.

**Pull request merged**
